Repository symblai/Symbl-powered-Agora-RTE-app, pull requests merged in 2021-11, with the labels that each got.

#45 Created SECURITY.md
  SECURITY.md
Labels: hacktoberfest

#50 Created SECURITY.md
  SECURITY.md
Labels: hacktoberfest, hacktoberfest-accepted

#51 Added Symbl logo on website and fixed warnings and error messages
  Symbl-Powered-Agora-master/bridge/rtc/web/RtcEngine.ts
  Symbl-Powered-Agora-master/bridge/rtc/web/symbl.ts
  Symbl-Powered-Agora-master/favicon.ico
  Symbl-Powered-Agora-master/src/subComponents/Transcript.tsx
Labels: enhancement

#52 Docs(AGORA-68):- Updated Backend setup instructions
  README.md
Labels: documentation

#42 docs: ✏️ updated the contributing.md file for easy workflow
  Contributing.md
Labels: hacktoberfest, hacktoberfest-accepted
